# Generated by Django 5.0.4 on 2024-04-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
